### ISSUE TITLE
Ubuntu 18.04 issue with install nginx with mod_security

### ISSUE THREAD

**Issue by snapshotleisure** [Jsitech/JShielder#9]
Hi, 

Want to first say great stuff with these scripts! They really make things easier.

I tried to install nginx with mod_security for Ubuntu 18.04 and couldn't get it working. In the end I decided to run the commands in the script manually and found the following:

The install package, needs to be corrected: apache2-prefork-dev should be changed to apache2-dev
_apt -y install git build-essential libpcre3 libpcre3-dev libssl-dev libtool autoconf **apache2-dev** libxml2-dev libcurl4-openssl-dev_

For the configure command, it is pointing to Ubuntu 14.04 directory when i think it should be pointing to the 18.04 directory
_./configure --user=www-data --group=www-data --with-pcre-jit --with-debug --with-http_ssl_module --add-module=/root/JShielder/**UbuntuServer_18.04LTS**/src/ModSecurity/nginx/modsecurity_

I had gcc 7 installed and there is a compilation bug with nginx working with gcc7. It is recommended to install nginx 1.13+, I installed the latest 1.15.0. https://trac.nginx.org/nginx/ticket/1259

Again great work and keep it up!

Thanks

**Comment by Jsitech** [comment]
Thanks!

I need to dedicate some time on the Nginx portion of the script since i know this it is widely used. I will set aside some time to update that part of the script and do proper testing to ensure everything work as intended.

On the configure Issue, you are absolutely right, since i reused the code from one of the Jshielder versions and completely forgot to update this piece of it, but it needs additional work anyways.

Thanks again for letting me know so i could put it on my To-Do list.

**Comment by php-** [comment]
Any updates on this?

**Comment by Jsitech** [comment]
> 
> 
> Any updates on this?

Rewriting the whole nginx deployment with mod-security for the 2 latest Ubuntu LTS versions. Should be available soon.

**Comment by Jsitech** [comment]
LEMP Deployment with ModSecurity fully functional https://github.com/Jsitech/JShielder/commit/34ed09cdde2b26197d63317afc59ca7ca5814508

**Comment by Jsitech** [comment]
LEMP Deployment Tested, Closing issue.
